ignore_colors = [
    #000000, # filter all black, DO NOT USE "#"!!!
]
allowed_colors = [
    "FF4500",
    "FFA800",
    "FFD635",
    "00A368",
    "3690EA",
    "B44AC0",
    "000000",
    "FFFFFF"
]
width = 1000
height = 1000
add-x = 500
add-y = 500

default_prio = 120 # priority: higher number = higher chance of being placed


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127

[[structure]]
name = "india"
file = "india.png"
startx = 287
starty = -292
priority = 127
